name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  
jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: | 
        cd src
        pwd
        docker build . --file Echarnus.Web/Echarnus.Web/Server/Dockerfile --tag echarn-us:$(date +%s) --tag echarn-us:latest
        
